name: Build Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          # Instalamos ldid para firmar y dpkg para empaquetar
          brew install ldid dpkg

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/*.sdk ~/theos/sdks/
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          # Usamos la ruta absoluta de ldid instalada por brew
          export PATH="/opt/homebrew/bin:$PATH"
          make package FINALPACKAGE=1 ARCHS="arm64 arm64e"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ResetGuest-Dylib-Final
          path: |
            .theos/obj/*.dylib
            packages/*.deb
          if-no-files-found: error